# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/b2a5474b-dd78-4f2a-8aa0-7d8b8bc87482";
      fsType = "btrfs";
      options = ["subvol=@nix" "noatime" "compress-force=zstd:1"];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/b2a5474b-dd78-4f2a-8aa0-7d8b8bc87482";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/b2a5474b-dd78-4f2a-8aa0-7d8b8bc87482";
      fsType = "btrfs";
      options = ["subvol=@swap" "ro"];
    };

  fileSystems."/persistent" =
    { device = "/dev/disk/by-uuid/b2a5474b-dd78-4f2a-8aa0-7d8b8bc87482";
      fsType = "btrfs";
      options = ["subvol=@persistent" "compress-force=zstd:1"];
      neededForBoot = true;
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/b2a5474b-dd78-4f2a-8aa0-7d8b8bc87482";
      fsType = "btrfs";
      options = ["subvol=@snapshots" "compress-force=zstd:1"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
    };

  

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
