name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: write ssh private key
        id: write-ssh-private-key
        shell: bash
        env:
          INPUT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -eu
          mkdir -p ~/.ssh
          echo "$INPUT_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -T git@github.com

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-labels: |
            merge-queue
